### ISSUE TITLE
users CRUD

### ISSUE THREAD

**Issue by devincowan** [DendraScience/dendra-web-ui#30]
UI for user Create, Edit, Deactivate

**Comment by devincowan** [comment]
https://docs.google.com/document/d/1tXpJsonprdlMhpR6bHiy6NMw3UOqag_y2DMMdvCP97I/edit#

**Comment by devincowan** [comment]
Making some notes here from our call today

- We talked about having this check use `$can` instead of using `auth` in the main NAV bar
https://github.com/DendraScience/dendra-web-ui/blob/dev-justin/src/components/MainNavigationDrawer.vue#L120

- Users in their own separate "admin section" (we will add some other items to this as well)

- Use the schema to lock down the ROLES to an array of 1 -- so we need to rename "ROLES" to "Role" on the user list page

**Comment by ergjustin** [comment]
@jscottsf 
Right now, if a manager needs to change user’s password, manager needs to have the current password of the user.
[dendra-web-api](https://github.com/DendraScience/dendra-web-api/blob/master/src/server/services/user/hooks/index.js#L69)

**Comment by devincowan** [comment]
Resolved via https://github.com/DendraScience/dendra-web-ui/pull/35
