### ISSUE TITLE
Presentation of UI (HIS vs Dendra)

### ISSUE THREAD

**Issue by devincowan** [DendraScience/dendra-web-ui#32]
This could be done by:

- Injecting environment vars that direct conditional theme/style.
- CUAHSI could fork the whole repo and maintain a fork with custom theme.

**Comment by jscottsf** [comment]
I don't mind the entire presentation system with each formal presentation getting merged into main. This can be rethought in a v3 of the UI (this is v2 technically).

**Comment by devincowan** [comment]
My preference would be creating a `presentations` dir as you suggest. Feels like using the [nuxt config](https://nuxtjs.org/docs/configuration-glossary/configuration-router/) might turn into a headache. Thanks for cooking up some ideas!
