### ISSUE TITLE
password complexity check + confirm password match

### ISSUE THREAD

**Issue by devincowan** [DendraScience/dendra-web-ui#37]
During user creation, we should check for password complexity. (min length etc 10?)
And we should have a password VERIFY (match) check

**Comment by ergjustin** [comment]
Is password complexity should be 

- length 10
- minimum one lowercase
- minimum one uppercase 
- minimum one special character

**Comment by devincowan** [comment]
Thanks for asking @ergjustin 
I think in our meeting we decided 
- length 10
No other requirements at this time

**Comment by devincowan** [comment]
resolved via https://github.com/DendraScience/dendra-web-ui/pull/35
